# Generated by Django 5.2 on 2025-05-03 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('head', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=3000)),
                ('head1', models.CharField(max_length=100)),
                ('content1', models.CharField(max_length=3000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='apk/images')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
